CREATE TABLE `orders` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no` varchar(64) NOT NULL COMMENT '业务订单号',
    `user_id` varchar(64) NOT NULL COMMENT '用户ID（openid 或系统用户ID）',
    `user_name` varchar(50) NOT NULL COMMENT '用户姓名',
    `id_card_no` varchar(32) NOT NULL COMMENT '身份证号',
    `student_school` varchar(100) DEFAULT NULL COMMENT '就读学校',
    `student_grade` varchar(50) DEFAULT NULL COMMENT '就读年级',
    `mobile` varchar(20) DEFAULT NULL COMMENT '手机号',
    `total_amount` decimal(10, 2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
    `pay_amount` decimal(10, 2) NOT NULL DEFAULT '0.00' COMMENT '实付金额',
    `status` tinyint NOT NULL DEFAULT '0' COMMENT '订单状态 0待支付 1已支付 2退款中 3已退款',
    `wx_prepay_id` varchar(64) DEFAULT NULL COMMENT '微信预支付单号',
    `wx_transaction_id` varchar(64) DEFAULT NULL COMMENT '微信支付流水号',
    `refund_no` varchar(64) DEFAULT NULL COMMENT '系统退款单号',
    `wx_refund_id` varchar(64) DEFAULT NULL COMMENT '微信退款单号',
    `refund_amount` decimal(10, 2) DEFAULT '0.00' COMMENT '退款金额',
    `refund_status` tinyint NOT NULL DEFAULT '0' COMMENT '退款状态 0无退款 1退款中 2退款成功 3退款失败',
    `refund_reason` varchar(255) DEFAULT NULL COMMENT '退款原因',
    `audit_status` tinyint NOT NULL DEFAULT '0' COMMENT '审核状态 0待审核 1审核通过 2审核拒绝',
    `audit_remark` varchar(255) DEFAULT NULL COMMENT '审核备注',
    `audit_by` int unsigned DEFAULT NULL COMMENT '审核人ID',
    `audit_time` datetime DEFAULT NULL COMMENT '审核时间',
    `receiver_name` varchar(50) DEFAULT NULL COMMENT '收货人姓名',
    `receiver_mobile` varchar(20) DEFAULT NULL COMMENT '收货人手机号',
    `receiver_address` varchar(255) DEFAULT NULL COMMENT '收货地址',
    `items_snapshot` text COMMENT '下单时SKU快照(JSON字符串)',
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单创建时间',
    `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
    `refund_time` datetime DEFAULT NULL COMMENT '退款完成时间',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_created_at` (`created_at`)
) ENGINE = InnoDB AUTO_INCREMENT = 28 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '订单表'

CREATE TABLE `xcx_users` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `openid` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '微信 openid（唯一）',
    `nickname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '昵称',
    `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '头像',
    `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '手机号',
    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `balance` decimal(10, 2) NOT NULL DEFAULT '0.00' COMMENT '用户余额',
    `vip_level` tinyint unsigned NOT NULL DEFAULT '0' COMMENT 'VIP等级(0:普通, 1:白银, 2:黄金...)',
    `vip_expires_at` datetime DEFAULT NULL COMMENT 'VIP过期时间',
    `is_purchased` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否购买过东西 (0:否, 1:是)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_openid` (`openid`)
) ENGINE = InnoDB AUTO_INCREMENT = 35 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci